name: Contents

on:
  workflow_dispatch:
  schedule:
    - cron: '00 3 * * 5'

jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04
    if: github.repository == 'LuisAlejandro/pypicontents'
    strategy:
      matrix:
        include:
          - lrange: "0-9"
          - lrange: "a"
          - lrange: "b"
          - lrange: "c"
          - lrange: "d"
          - lrange: "e"
          - lrange: "f"
          - lrange: "g"
          - lrange: "h"
          - lrange: "i"
          - lrange: "j"
          - lrange: "k"
          - lrange: "l"
          - lrange: "m"
          - lrange: "n"
          - lrange: "o"
          - lrange: "p"
          - lrange: "q"
          - lrange: "r"
          - lrange: "s"
          - lrange: "t"
          - lrange: "u"
          - lrange: "v"
          - lrange: "w"
          - lrange: "x"
          - lrange: "y"
          - lrange: "z"
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          ref: master
          fetch-depth: 0
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      - name: Processing python packages
        env:
          LRANGE: ${{ matrix.lrange }}
        run: |
          docker build -t dockershelf/pypicontents:3.10 docker/3.10
          docker run -v ${PWD}:${PWD} -w ${PWD} -u $(id -u):$(id -g) \
            dockershelf/pypicontents:3.10 \
              pypicontents pypi -o data/${LRANGE}/pypi.json \
                -f logs/${LRANGE}/pypi.log -R ${LRANGE} -L 1G -M 6G -T 18000
      - name: Commiting changes
        env:
          LRANGE: ${{ matrix.lrange }}
        run: |
          git config --global user.name "Luis Alejandro Martínez Faneyth"
          git config --global user.email "luis@luisalejandro.org"
          git config --global pull.rebase false
          git add --all .
          git commit -a -m "[ci skip] Updating PyPIContents index (PyPI letter ${LRANGE})."
          git pull -s recursive -X ours origin master
          git push -f origin master

  stdlib:
    name: Generating Standard Library database
    runs-on: ubuntu-20.04
    if: github.repository == 'LuisAlejandro/pypicontents'
    needs: build
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          ref: master
          fetch-depth: 0
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      - name: Generating standard library database and merging indexes
        env:
          LRANGE: ${{ matrix.lrange }}
        run: |
          for PYVER in 3.8 3.9 3.10 3.11; do
              docker build -t dockershelf/pypicontents:${PYVER} docker/${PYVER}
              docker run -v ${PWD}:${PWD} -w ${PWD} -u $(id -u):$(id -g) \
                  dockershelf/pypicontents:${PYVER} \
                      pypicontents stdlib -o stdlib/${PYVER}/stdlib.json
          done

          docker run -v ${PWD}:${PWD} -w ${PWD} -u $(id -u):$(id -g) \
              dockershelf/pypicontents:3.10 \
                  pypicontents merge -o pypi.json -i data
          docker run -v ${PWD}:${PWD} -w ${PWD} -u $(id -u):$(id -g) \
              dockershelf/pypicontents:3.10 \
                  pypicontents merge -o stdlib.json -i stdlib
          docker run -v ${PWD}:${PWD} -w ${PWD} -u $(id -u):$(id -g) \
              dockershelf/pypicontents:3.10 \
                  pypicontents errors -o errors.json -i logs
          docker run -v ${PWD}:${PWD} -w ${PWD} -u $(id -u):$(id -g) \
              dockershelf/pypicontents:3.10 \
                  pypicontents stats -o stats.txt -i logs

          git config --global user.name "Luis Alejandro Martínez Faneyth"
          git config --global user.email "luis@luisalejandro.org"
          git config --global pull.rebase false
          git reset 0ea1baab6172864f1b7e9d5948885dfe7c87d6a3
          rm -rf pypi.json.xz
          xz pypi.json
          git add --all .
          git commit -a -m "[ci skip] Updating PyPIContents index (stdlib and merge)."
          git push -f origin master
